spring.application.name=MCP Server

# Server Config
server.port=9090
server.servlet.session.cookie.name=MCP_SERVER_STREAMABLE_HTTP_SECURED_TOOLS_SESSIONID

# Spring Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/mcp-realm

# MCP Server
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=mcp_server
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.streamable-http.keep-alive-interval=30s

# logging
logging.level.org.springframwork.security=debug