spring.application.name=mcp-authorization-server

server.port=9089
# Override the default cookie name (JSESSIONID).
# This allows running multiple Spring apps on localhost, and they'll each have their own cookie.
# Otherwise, since the cookies do not take the port into account, they are confused.
server.servlet.session.cookie.name=MCP_AUTHORIZATION_SERVER_SESSIONID