spring.application.name=MCP Client

# Server Config
server.port=9091

# MCP Client
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.initialized=false
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.streamable-http.connections.current-weather.url=http://localhost:9090

# Spring Security
spring.security.oauth2.client.provider.authserver.issuer-uri=http://localhost:9089
spring.security.oauth2.client.registration.authserver-client-credentials.client-id=mcp-test
#spring.security.oauth2.client.registration.authserver-client-credentials.client-secret=<THE CLIENT SECRET>
spring.security.oauth2.client.registration.authserver-client-credentials.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authserver-client-credentials.provider=authserver

# logging
logging.level.org.springframwork.security=debug
